apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-yaml
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  source:
    repoURL: https://github.com/hyun6ik/ArgoCD-Study.git
    targetRevision: master
    path: sample-yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground