apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: dev Project
  sourceRepos:
    - '*'

  destionations:
    - namespace: default
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace

  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy