apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sample-helm-1.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "sample-helm-1.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-helm-1.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: {{ .Chart.Name }}
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "sample-helm-1.fullname" . }}
spec:
  type: NodePort
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetProt }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "sample-helm-1.selectorLabels" . | nindent 8 }}