apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template."sample-helm-2.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "sample-helm-2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-helm-2.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template."sample-helm-2.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "sample-helm-2.selectorLabels" . | nindent 8}}